site_name: Data Engineering Field Notes

theme:
  name: material

nav:
  - Home: index.md
  - Apache Airflow:
      - Architecture: airflow/architecture.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format